### ISSUE TITLE
[pose_follower] undefined symbol: base_local_planner::TrajectoryPlannerROS::TrajectoryPlannerROS()

### ISSUE THREAD

**Issue by longjianquan** [ros-planning/navigation_experimental#28]
[ INFO] [1539851510.799287680, 1.600000000]: Using plugin "static_layer"
[ INFO] [1539851510.813949817, 1.600000000]: Requesting the map...
[ INFO] [1539851510.986230475, 1.800000000]: Resizing costmap to 200 X 200 at 0.050000 m/pix
[ INFO] [1539851511.084591408, 1.900000000]: Received a 200 X 200 map at 0.050000 m/pix
[ INFO] [1539851511.096221962, 1.900000000]: Using plugin "obstacle_layer"
[ INFO] [1539851511.103033637, 1.900000000]:     Subscribed to Topics: scan bump
[ INFO] [1539851511.173458091, 1.900000000]: Using plugin "inflation_layer"
[ INFO] [1539851511.224578947, 2.000000000]: Using plugin "obstacle_layer"
[ INFO] [1539851511.226444980, 2.000000000]:     Subscribed to Topics: scan bump
[ INFO] [1539851511.258295430, 2.000000000]: Using plugin "inflation_layer"
/home/ljq/ljq_ws/devel/lib/move_base/move_base: symbol lookup error: /home/ljq/ljq_ws/devel/lib//libpose_follower.so: undefined symbol: _ZN18base_local_planner20TrajectoryPlannerROSC1Ev

**Comment by mintar** [comment]
This is strange. My guess is that your `LD_LIBRARY_PATH` environment variable is not set properly. Run the following command in the same terminal before running move_base:

```bash
source /home/ljq/ljq_ws/devel/setup.bash
```

If that doesn't help, can you run the following command and paste the output here?

```bash
ldd /home/ljq/ljq_ws/devel/lib/libpose_follower.so
```

The missing symbol is defined in library `libtrajectory_planner_ros.so`, part of the base_local_planner package. Is that package installed? You can install like this:

```bash
sudo apt install ros-kinetic-base-local-planner
```

Also, you can try using the binary installation of pose_follower by removnig it from your catkin workspace and running this:

```bash
sudo apt install ros-kinetic-pose-follower
```

**Comment by longjianquan** [comment]
i have tried you said,but it did not.
ljq@ljq:~/ljq_ws/devel/lib$ ls
autolabor_fake               libglobal_planner.so        lidar_simulation
libasr_ftc_local_planner.so  liblayers.so                move_base
libbase_local_planner.so     libmove_base.so             pkgconfig
libcostmap_2d.so             libpose_follower.so         python2.7
libdwa_local_planner.so      libsimple_local_planner.so

https://answers.ros.org/question/198419/adding-a-new-local-planner-in-navigation/

here someone meet the same error!

**Comment by longjianquan** [comment]
i have tried you said,but it did not.
ljq@ljq:~/ljq_ws/devel/lib$ ls
autolabor_fake               libglobal_planner.so        lidar_simulation
libasr_ftc_local_planner.so  liblayers.so                move_base
libbase_local_planner.so     libmove_base.so             pkgconfig
libcostmap_2d.so             libpose_follower.so         python2.7
libdwa_local_planner.so      libsimple_local_planner.so

https://answers.ros.org/question/198419/adding-a-new-local-planner-in-navigation/

here someone meet the same error!

**Comment by mintar** [comment]
Sorry, I cannot reproduce this. I guess something went wrong when you created your catkin workspace, or you didn't source the proper setup.bash file.

Also I'm still waiting for that `ldd` output from my other comment.
