### ISSUE TITLE
failed to read motion file error not resolved even after changing global costmap resolution

### ISSUE THREAD

**Issue by sudo-panda** [ros-planning/navigation_experimental#38]
I am getting the ```ERROR: failed to read motion primitive file``` even though I changed the global costmap resolution to 0.025 (taken from the mprim file). I have read the previous issue that pointed out the error but I do not get what other parameters in the file and my configuration of my bot are conflicting. Could you please help.

**Comment by mintar** [comment]
Can you upload the mprim file somewhere? Also, can you do a `rosparam dump params.yaml` and upload that file as well?

**Comment by sudo-panda** [comment]
[params.yaml](https://gist.github.com/sudo-panda/0d318f3c9584817d2b66c0d8710d186d)
[pr3.mprim](https://gist.github.com/sudo-panda/1a615ebb223a6e068cbd4a74f72d6b20)

**Comment by sudo-panda** [comment]
I am no longer using this planner for my bot hence closing this issue. Thanks for helping.

**Comment by trickarcher** [comment]
I am facing this problem on my car-like robot. I have already used SBPL Lattice Planner with Teb Local Planner on my holonomic bot and it worked perfectly fine. But I can't seem to get past this error now. Is there any different mprim file for car-like robots?

**Comment by trickarcher** [comment]
It was actually my fault. I had missed the delta parameter in the gmapping param file which was essentially the resolution of the map. Matching the map resolution with the mprim resolution worked perfectly. Thanks!
