### ISSUE TITLE
apt unable to overwrite liblaser_scan_filters.so

### ISSUE THREAD

**Issue by mbudris** [ros-planning/navigation_experimental#42]
**ros-kinetic-navigation-experimental** depends on **ros-kinetic-assisted-teleop**.

when trying to install assited-teleop:
dpkg: error processing archive /var/cache/apt/archives/ros-kinetic-assisted-teleop_0.2.1-0xenial-20190608-153029-0800_amd64.deb (--unpack):
 trying to overwrite '/opt/ros/kinetic/lib/liblaser_scan_filters.so', which is also in package ros-kinetic-laser-filters 1.8.5-0xenial-20190608-123733-0800

**Comment by mintar** [comment]
Thank you! Fixed it.

**Comment by mintar** [comment]
I'm planning to release a new version of navigation_experimental next week. Of course, this will take a couple of weeks to propagate. Until then, you'll have to install navigation_experimental from source.

**Comment by mbudris** [comment]
Thank you, keep up the nice work!
