### ISSUE TITLE
Transfer to melodic

### ISSUE THREAD

**Issue by itsmeashutosh43** [ros-planning/navigation_experimental#45]
Since especially the tf functions are very different in melodic and kinetic, I had(Ubuntu 18.04) to edit a lot before using some packages. Had the codes been in melodic, others would benefit as well. Although I am new to open source contributions, I am free and willing to contribute. Or has someone already started it?
Sorry if I sound too naive, but I am desperate to up my skill via open source contributions.

**Comment by mintar** [comment]
This repo already supports melodic! If you build from source, just switch to the **melodic-devel** git branch. If you use the binaries, just do this: `sudo apt install ros-melodic-navigation-experimental`.
