### ISSUE TITLE
Switch default branch to "melodic-devel"

### ISSUE THREAD

**Issue by mintar** [ros-planning/navigation_experimental#46]
Could somebody please update the default branch of this repo to "melodic-devel"? I'm the maintainer of this repo, but I don't have the necessary permissions to do that.

@ros-planning/navigation-maintainers @wjwwood @dirk-thomas

**Comment by wjwwood** [comment]
Sure, I'll add you to the @ros-planning/navigation-maintainers too.

**Comment by mintar** [comment]
Great, thanks!
