### ISSUE TITLE
Using my own map in sbpl_lattice_planner

### ISSUE THREAD

**Issue by ChunYe173** [ros-planning/navigation_experimental#49]
Hi,

I am trying to use my own map in sbpl_latice_planner. I changed the args of the node "map_server" in move_base_sbpl_fake_localization_2.5cm.launch to my own pgm file. I have also change the pgm file in willow.world to my own pgm file. I have attached what I saw in rviz. 
![Screenshot from 2020-11-09 19-30-38](https://user-images.githubusercontent.com/66294422/98537386-25eaa080-22c4-11eb-9490-82944df6b0b6.png)
![Screenshot from 2020-11-09 19-33-04](https://user-images.githubusercontent.com/66294422/98537485-4c104080-22c4-11eb-8e51-6a34aef8deb1.png)

Issue:
1. The map is very far away from the robot.
![Screenshot from 2020-11-09 19-38-25](https://user-images.githubusercontent.com/66294422/98537520-5b8f8980-22c4-11eb-8ad0-5a955c7558b5.png)

2. The robot can't navigate into the map. It will only navigate around the map. I think maybe the map is too small for the size of the robot.
![Screenshot from 2020-11-09 19-41-51](https://user-images.githubusercontent.com/66294422/98537577-68ac7880-22c4-11eb-8f24-24a46f9e351a.png)

3. The surrounding of the robot does not turn black when it is approaching obstacles.
![Screenshot from 2020-11-09 19-41-33](https://user-images.githubusercontent.com/66294422/98537598-7235e080-22c4-11eb-97ba-466b2278a911.png)

Please kindly assist. Thank you.

**Comment by mintar** [comment]
This sort of questions is better suited for https://answers.ros.org/.
