### ISSUE TITLE
failed to read in motion primitive file

### ISSUE THREAD

**Issue by hcostelha** [ros-planning/navigation_experimental#50]
Hi,

I trying to use the SBPLLatticePlanner global planner, but I am getting this error:
```
[ INFO] [1611170476.949083456, 1909.800000000]: Name is SBPLLatticePlanner
terminate called after throwing an instance of 'SBPL_Exception'
  what():  ERROR: failed to read in motion primitive file
```
I know that typically this problem is due to the use of different resolutions in the mprim file and the map from the map server, however I have checked and have both using 0.05 m/px. 
I have generated a new mprim file to test, based on the genmprim_unicycle, having just changed the resolution to 0.05 m/px. I run my map_server and the command "rostopic echo map_metadata" gives my a resolution of 0.05000000074505806.
Initially I though the problem was with the small difference to 0.05, but running the "move_base_sbpl_fake_localization_2.5cm.launch" works just fine and the map_server resolution is also 0.02500000037252903.

I have generated the mprim file using octave (see below), but it should not be an issue (I tested other parameters and compared with the matlab output, and found no relevant differences).

I am using ROS noetic in Xubuntu 20.04, with the software up to date as of today. As stated above, the example "move_base_sbpl_fake_localization_2.5cm.launch" works fine. I am attaching the map files and the generated mprim file.
[issue.zip](https://github.com/ros-planning/navigation_experimental/files/5845083/issue.zip)

I am putting this here because it could be an issue with the planner, but if it would be more suitable to put it in answers.ros.org, I can put it there.

**Comment by mintar** [comment]
Your `unicycle_0.05.mprim` file starts with a [UTF-8 byte order mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark) (the bytes `0xEF 0xBB 0xBF` at the start of the file):

```
$ xxd unicycle_0.05.mprim | head -n 1
00000000: efbb bf72 6573 6f6c 7574 696f 6e5f 6d3a  ...resolution_m:

$ xxd pr2.mprim | head -n 1
00000000: 7265 736f 6c75 7469 6f6e 5f6d 3a20 302e  resolution_m: 0.
```

This command will fix it:

```bash
sed -i '1s/^\xEF\xBB\xBF//' unicycle_0.05.mprim
```
