### ISSUE TITLE
how to prohibit sbpl global planning through unknown area?

### ISSUE THREAD

**Issue by TrayfourYu** [ros-planning/navigation_experimental#53]
I'm using move_base package in a differ robot with a static global map, which is got from the gmapping. So, there are some unknown area in the map, and I found that sbpl planner can't find a path through those area.
![image](https://user-images.githubusercontent.com/50270077/115415900-df618080-a229-11eb-9e91-4b1643ba10d8.png)

**Comment by mintar** [comment]
I guess you'll have to write a small node that subscribes to the map topic, processes the map the way you want, and re-publishes it on a different topic. You can then use the filtered topic for move_base.

**Comment by TrayfourYu** [comment]
> I guess you'll have to write a small node that subscribes to the map topic, processes the map the way you want, and re-publishes it on a different topic. You can then use the filtered topic for `move_base.

I will have a try. Thanks a lot.

**Comment by SteveMacenski** [comment]
@mintar navigation also has a param for tracking unknown costs, I typically use that in the planner to do some logic like `if tracking unknown and cell unknown, don't go` type-logic.

**Comment by TrayfourYu** [comment]
Well, I end up this with just clearing out the unknown area of the map in the **Gimap** that is a picture editing software.
