### ISSUE TITLE
Optimization of parameter.

### ISSUE THREAD

**Issue by mw-JHC** [ros-planning/navigation_experimental#61]
Hi,
first of all thank you for the development of SBLP-Planner in ROS.

I  am using now  SBPL planner for my robot and it's going very well.
But i want to optimize the parameters of the planner(allocated time, initial_epsilon unw...)

can i change the parameter during the running of launch file?

i tried to use rosparam api and dynamic reconfiguration api but it didn't work.

if you know a possiblity to change the parameter of SBLP during a running of launch file, can you tell me about it?

or there are some smart method for the optimization?

**Comment by mintar** [comment]
No, unfortunately the parameters can not be changed dynamically during runtime. The only way is to stop the launch file, change the parameters, and start it again. Sorry!
